services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
        - ${DB_PORT}:3306
    restart: always
    volumes:
        - db-store:/var/lib/mysql
        - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store:
